 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov1.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov2.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov3.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov4.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov5.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov6.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov7.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov8.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov9.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True
 python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov10.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1 --bootstrap True


#python ../feature_selection_toolkit/select_features.py rads-features/_HRD_discovery_ovary_df_discov.csv --output_df_path rads-features/ovary_feat_eval_df_discov.csv --method cph --output_plot_path rads-features/ovary_discov.png --outlier_std_threshold -1
